name = "truyendemxyz"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./"
binding = "ASSETS"
not_found_handling = "404-page"

[[durable_objects.bindings]]
name = "VIEW_STORE"
class_name = "ViewStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ViewStore"]
